In [194]:
# This notebook will demonstrate slicing

import numpy as np
import skimage as ski
print(np.__file__)
print(np.__version__)
print(ski.__version__)
from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

import matplotlib.pyplot as plt

from __future__ import print_function

import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop
import tensorflow as tf
from skimage.transform import resize
from graphviz import Graph, render
from utils.netviz import NetViz
from utils.mnistutil import MNISTUitl
from utils.sliceutil import Slice
sx = 28
sy = 28

/Users/mislam/anaconda/lib/python3.6/site-packages/numpy/__init__.py
1.16.2
0.14.2


In [195]:
mn = MNISTUitl()
viz = NetViz()

In [196]:
X, Y, x, y = mn.getdata2(0,0,sx,sy)
X.shape

/Users/mislam/anaconda/lib/python3.6/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "


(60000, 28, 28)

In [197]:
nm , xt, yt = mn.train2(X, Y, x,y,sx,sy,10,50)
nn , xt1, yt1 = mn.train2(X, Y, x,y,sx,sy,10,50)

x_train shape: (60000, 28, 28, 1)
(60000, 28, 28, 1) 60000 train samples (60000,)
10000 test samples
(60000,) (60000,)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Input (Flatten)              (None, 784)               0         
_________________________________________________________________
H (Dense)                    (None, 49)                38465     
_________________________________________________________________
output (Dense)               (None, 10)                500       
Total params: 38,965
Trainable params: 38,965
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/50
60000/60000 [==============================] - 2s 28us/step - loss: 1.4140 - acc: 0.6621

In [198]:
X, Y, x, y = mn.getdata2(0,0,sx,sy)
model , xt2, yt2 = mn.train2(X, Y, x,y,sx,sy,10,50)

/Users/mislam/anaconda/lib/python3.6/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "


x_train shape: (60000, 28, 28, 1)
(60000, 28, 28, 1) 60000 train samples (60000,)
10000 test samples
(60000,) (60000,)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Input (Flatten)              (None, 784)               0         
_________________________________________________________________
H (Dense)                    (None, 49)                38465     
_________________________________________________________________
output (Dense)               (None, 10)                500       
Total params: 38,965
Trainable params: 38,965
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/50
60000/60000 [==============================] - 2s 29us/step - loss: 1.4374 - acc: 0.6559

In [235]:
X, Y, x, y = mn.getdata2(0,0,sx,sy)
model2 , xt3, yt3 = mn.train2(X, Y, x,y,sx,sy,10,50)

/Users/mislam/anaconda/lib/python3.6/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "


x_train shape: (60000, 28, 28, 1)
(60000, 28, 28, 1) 60000 train samples (60000,)
10000 test samples
(60000,) (60000,)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Input (Flatten)              (None, 784)               0         
_________________________________________________________________
H (Dense)                    (None, 49)                38465     
_________________________________________________________________
output (Dense)               (None, 10)                500       
Total params: 38,965
Trainable params: 38,965
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/50
60000/60000 [==============================] - 2s 30us/step - loss: 1.4167 - acc: 0.6637

In [199]:
#W1, W2, b1, b2 = slc.getweights(nm)

In [200]:
#W1, W2,b1,b2 = slc.dynamicmodify(nm,xt[0],sx,sy)

In [201]:
#W1.shape
nm.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Input (Flatten)              (None, 784)               0         
_________________________________________________________________
H (Dense)                    (None, 49)                38465     
_________________________________________________________________
output (Dense)               (None, 10)                500       
Total params: 38,965
Trainable params: 38,965
Non-trainable params: 0
_________________________________________________________________


In [202]:
#W2.shape

In [580]:
ym  = []
yn = []
slcm = Slice()
slcn = Slice()
mW1, mW2, mb1, mb2 = slcm.getweights(nm)
nW1, nW2, nb1, nb2 = slcn.getweights(nn)
lm = 6
ln = 7
th1 = .0001
th2 = .0001
for i in range(0,len(yt)):
    if yt[i] == lm and nm.predict(xt[i:i+1])[0][lm] >.9:
        ym.append(xt[i])
    if yt[i] == ln and nm.predict(xt[i:i+1])[0][ln] >.9:
        yn.append(xt[i])
print(len(ym),len(yn))

np.random.shuffle(ym)
np.random.shuffle(yn)
ym = ym[0:100]
yn = yn[0:100]
#slc.D1

mc = 0
for x in ym:
    #W1, W2,b1,b2 = slc.dynamicmodify(nm,x,sx,sy)
    mW1, mW2,mb1,mb2 = slcm.modifyThroughInterSection(nm,x,sx,sy, th1)
    mc = mc + 1
    #print(np.count_nonzero(slcm.D2))
    if np.count_nonzero(slcm.D2) < 45:
        print("Breaking at mc ", mc,np.count_nonzero(slcm.D2))
        slcm.first = True

nc = 0
for x in yn:
    #W1, W2,b1,b2 = slc.dynamicmodify(nm,x,sx,sy)
    nW1, nW2,nb1,nb2 = slcn.modifyThroughInterSection(nn,x,sx,sy, th2)
    nc = nc + 1
    if np.count_nonzero(slcn.D2) < 45:
        print("Breaking at nc ", nc,np.count_nonzero(slcn.D2))
        slcn.first = True

846 873
Breaking at nc  22 0
Breaking at nc  52 0


In [581]:
#dot, A = slc.showstatweights(nm,zero[0],[0],sx,sy,ss = .2)
#dot
#slcm.D1

In [582]:
#doto, A = viz.vispredictwights(nm, xt[0], yt[0] , sx, sy )
#doto

In [583]:
slcm.D1[0]
nz = np.count_nonzero(slcm.D1)
nz

11760

In [584]:
tot = 784*49
tot

38416

In [585]:
nz / tot

0.30612244897959184

In [586]:
np.count_nonzero(slcn.D2)
#slc.D2

49

In [587]:
np.count_nonzero(slcm.W2)

490

In [588]:
w,b = nm.layers[1].get_weights()

In [589]:
print(yt[0:1])
nm.predict(xt[0:1])

[7]


array([[4.0180093e-06, 2.0888856e-10, 1.2280799e-05, 4.1744462e-03,
        3.2877936e-11, 8.2652969e-06, 1.6627533e-15, 9.9579227e-01,
        1.2810719e-06, 7.3665506e-06]], dtype=float32)

In [590]:
model.layers[1].set_weights([slcm.D1,slcm.d1])
model.layers[2].set_weights([slcm.D2,slcm.d2])
from sklearn.metrics import accuracy_score
zeros = []
pred = []
tr = []
labs = [0,1,2,3,4,5,6,7,8,9]
acc = []
count = 0
for ly in labs:
    pred = []
    tr = []
    for i in range(0,len(yt)):
        count += 1
        if yt[i] == l:
            p = model.predict(xt[i:i+1])
            m = p.argmax()
            pred.append(m)
            tr.append(ly)
    score = accuracy_score(pred,tr)
    acc.append(score)
print(acc)
print(count)

[0.6570841889117043, 0.0, 0.0, 0.0, 0.0, 0.0, 0.34291581108829566, 0.0, 0.0, 0.0]
100000


In [591]:
model.layers[1].set_weights([slcn.D1,slcn.d1])
model.layers[2].set_weights([slcn.D2,slcn.d2])
from sklearn.metrics import accuracy_score
zeros = []
pred = []
tr = []
labs = [0,1,2,3,4,5,6,7,8,9]
acc = []
count = 0
for ly in labs:
    pred = []
    tr = []
    for i in range(0,len(yt)):
        count += 1
        if yt[i] == l:
            p = model.predict(xt[i:i+1])
            m = p.argmax()
            pred.append(m)
            tr.append(ly)
    score = accuracy_score(pred,tr)
    acc.append(score)
print(acc)
print(count)

[0.8090349075975359, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.19096509240246407, 0.0, 0.0]
100000


In [578]:
model.layers[1].set_weights([slcm.D1,slcm.d1])
model.layers[2].set_weights([slcm.D2,slcm.d2])



model2.layers[1].set_weights([slcn.D1,slcn.d1])
model2.layers[2].set_weights([slcn.D2,slcn.d2])


w1, b1, w2, b2 = slcm.joinModules(model,model2)
model.layers[1].set_weights([w1,b1])
model.layers[2].set_weights([w2,b2])
from sklearn.metrics import accuracy_score
zeros = []
pred = []
tr = []
labs = [0,1,2,3,4,5,6,7,8,9]
acc = []
count = 0
for ly in labs:
    pred = []
    tr = []
    for i in range(0,len(yt)):
        count += 1
        if yt[i] == l:
            p = model.predict(xt[i:i+1])
            m = p.argmax()
            pred.append(m)
            tr.append(ly)
    score = accuracy_score(pred,tr)
    acc.append(score)
print(acc)
print(count)

[0.9722792607802875, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.027720739219712527, 0.0, 0.0]
100000


In [579]:
#doto, A = viz.vispredictwights(model, xt[1], yt[1] , sx, sy )
#dot, A, g = viz.vispredict(model, xt[0], [7],sx,sy,ss = .02)

#doto

In [452]:
#print(l)
#dot.render('img/intersect/{0}/ma.gv'.format(l))

In [453]:
#dot

In [234]:
s = 61
t = 62
print(yt[s:t])
model.predict(xt[s:t])

[8]


array([[3.5109918e-03, 1.4763539e-04, 4.8357287e-01, 8.7476503e-03,
        1.1538214e-03, 3.0286053e-02, 1.3256031e-04, 1.0390651e-02,
        3.7918073e-01, 8.2877100e-02]], dtype=float32)

In [593]:
slc.D1.shape

(784, 49)

In [615]:
from utils import conv2d as cnv
W1 = slc.D1.reshape((784 ,49 ,1,1))
print(W1.shape, W1.shape[:2],xt[0:1].shape)
M1 = cnv.conv2d(xt[0:1],W1, stride=(3, 3))

(784, 49, 1, 1) (784, 49) (1, 28, 28, 1)


In [616]:
M1.shape

(1, 10, 10, 1)

In [617]:
np.count_nonzero(slc.D1)

8624

In [619]:
M1

array([[[[ 1.70632433e-02],
         [ 8.93343389e-02],
         [ 1.01895910e-02],
         [-4.59318981e-05],
         [-1.82204321e-02],
         [ 2.35907305e-02],
         [ 6.79127872e-04],
         [-4.35700864e-02],
         [ 8.28742310e-02],
         [-1.81796066e-02]],

        [[ 1.00288346e-01],
         [ 9.11214948e-02],
         [-1.40645653e-02],
         [-3.45492139e-02],
         [-2.63911653e-02],
         [ 4.83121946e-02],
         [ 2.98024435e-03],
         [ 1.94502808e-02],
         [ 7.59518594e-02],
         [-2.73389742e-02]],

        [[ 1.02029786e-01],
         [ 2.19233800e-02],
         [-2.42439527e-02],
         [-5.20113483e-02],
         [ 1.50416363e-02],
         [-1.28236813e-02],
         [-1.83122456e-02],
         [ 9.70526189e-02],
         [ 4.31621373e-02],
         [ 2.60100607e-02]],

        [[ 5.69942966e-02],
         [-2.65213288e-02],
         [ 2.13293508e-02],
         [ 3.42378430e-02],
         [ 5.39476871e-02],
         [ 1.9